language: node_js
node_js:
- 12
dist: xenial
before_install:
- rvm install 2.2.2
before_script:
- npm install
- npm run test
notifications:
  slack:
    secure: QKdaSOh07d5YCVzA7yQUxapw84NRK9ZknlmgpDZMWLFaqjucgo7+iavN2JMFa24TUakdhZeycNii3JllHArmT6un4Bt16a7J1hn9NybfrBPNH6G12fX3AeCUJLQhA72vqJpjg/GXllOzabLTGgLCnAWMuVxhcnTTLLh8566p4L1KRKd6dbqxATgXt5wiTv952pzGJhd/bDBktjSzc7UPqXy3bTYbU55O4A36Y8sU1pmEcD6Zu2cVKRQpkfxmOA6CmZLQvl5+54gxmMlRgNUXAyL8KNfPMRxj7nLnZnZJAIxxvsYfCNPo+zJkRfjlqq9WoCumB6oCRB5STKv1Ezb1JpqI1jS6o0MZjmWOOk6tWkOOU8rhWG97eoTiTHBu1e221fWsLBB2Vyjue5rgf6v4AduQdenPipGrb59NjWJ2eUQ0mv98s2tn9OEV1qjcWWHWQ4dQDGf5IFwmXoaS82UJwcyfrtFz/viZsBxvB+6DxZvi48F65PK3vFINfPwOlKbIUvT3/JiN1o6VrsTiv4pAr5LJdm0tEaqZTETgUn+VxkAfq4tIaDqtTl1os4LN7jCwlz1+hjs1gpHJjT4w7ALJciYJN5B3vC8l1biPdG8Zb07Iv4t670dZ+/ubMD+Tj+5ufGiH2LKSaBYfkfx1ecuHRLF4NaqY9JKRdKUmpgUXLBs=
